import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import wiki from './wiki.config.json';

const config: Config = {
  title: wiki.title,
  tagline: wiki.tagline,
  favicon: 'img/favicon.png',

  url: wiki.url,
  baseUrl: '/',

  organizationName: wiki.organizationName,
  projectName: wiki.projectName,

  onBrokenLinks: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  headTags: wiki.noindex
    ? [{ tagName: 'meta', attributes: { name: 'robots', content: 'noindex, nofollow' } }]
    : [],

  plugins: [
    './plugins/search-plugin',
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          editUrl: undefined,
          showLastUpdateTime: false,
          showLastUpdateAuthor: false,
          // Filter folder index docs out of every autogenerated section.
          // Each category in sidebars.ts links to its section's index via
          // `link: { type: 'doc', id: 'X/index' }`, so the category header
          // IS the navigation to the index. Without this filter, Docusaurus
          // 3.10 also includes the index as a duplicate child entry.
          sidebarItemsGenerator: async ({defaultSidebarItemsGenerator, ...args}) => {
            const items = await defaultSidebarItemsGenerator(args);
            const stripIndex = (list: any[]): any[] =>
              list
                .filter((item) => !(item.type === 'doc' && typeof item.id === 'string' && item.id.endsWith('/index')))
                .map((item) =>
                  item.type === 'category' && Array.isArray(item.items)
                    ? {...item, items: stripIndex(item.items)}
                    : item
                );
            return stripIndex(items);
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: wiki.noindex ? false : undefined,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: undefined,
    navbar: {
      title: wiki.title,
      logo: undefined,
      items: [],
    },
    footer: {
      style: 'light',
      links: [],
      copyright: wiki.copyright,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
