import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: [
        'start-here/intro',
        'start-here/who-this-is-for',
        'start-here/the-refound-america-manifesto',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: true,
      link: {type: 'doc', id: 'concepts/index'},
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Case Studies',
      collapsed: true,
      link: {type: 'doc', id: 'case-studies/index'},
      items: [{type: 'autogenerated', dirName: 'case-studies'}],
    },
    {
      type: 'category',
      label: 'Christoindustry Playbooks',
      collapsed: true,
      link: {type: 'doc', id: 'playbooks/index'},
      items: [{type: 'autogenerated', dirName: 'playbooks'}],
    },
    {
      type: 'category',
      label: 'Inspirations',
      collapsed: true,
      link: {type: 'doc', id: 'inspirations/index'},
      items: [{type: 'autogenerated', dirName: 'inspirations'}],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: ['reference/lexicon', 'reference/voice-rules'],
    },
  ],
};

export default sidebars;
